export const FOOD_DATA = [
    {
      name: "Boiled Egg",
      price: 15, // ₹
      text: "A nutritious and simple protein-rich breakfast option.",
      image: "/images/egg.png",
      type: "breakfast",
    },
    {
      name: "Ramen",
      price: 150,
      text: "A savory Japanese noodle dish served with broth, meat, and vegetables.",
      image: "/images/ramen.png",
      type: "lunch",
    },
    {
      name: "Grilled Chicken",
      price: 250,
      text: "Tender and juicy chicken grilled to perfection, seasoned with herbs.",
      image: "/images/chicken.png",
      type: "dinner",
    },
    {
      name: "Cake",
      price: 100,
      text: "Soft, moist, and sweet—a perfect treat for any time of day.",
      image: "/images/cake.png",
      type: "breakfast, midnight snack",
    },
    {
      name: "Burger",
      price: 120,
      text: "A classic fast food item with a juicy patty, fresh veggies, and sauces.",
      image: "/images/burger.png",
      type: "lunch",
    },
    {
      name: "Pancake",
      price: 80,
      text: "Soft, fluffy pancakes, perfect with syrup or honey.",
      image: "/images/pancake.png",
      type: "dinner",
    },
    {
      name: "Poha",
      price: 40,
      text: "A light and nutritious flattened rice dish popular in Indian breakfasts.",
      image: "/images/poha.png",
      type: "breakfast",
    },
    {
      name: "Idli",
      price: 50,
      text: "Steamed rice cakes, soft and healthy, often served with chutney.",
      image: "/images/idli.png",
      type: "breakfast",
    },
    {
      name: "Potato Fry",
      price: 70,
      text: "Crispy fried potatoes, a delicious side dish for any meal.",
      image: "/images/potato-fry.png",
      type: "dinner, lunch",
    },
    {
      name: "Paneer",
      price: 150,
      text: "Soft Indian cottage cheese cooked with spices, a vegetarian favorite.",
      image: "/images/paneer.png",
      type: "dinner",
    },
    {
      name: "Chole",
      price: 120,
      text: "Spicy and tangy chickpea curry, often served with rice or bread.",
      image: "/images/chole.png",
      type: "dinner",
    },
    {
      name: "Mushroom Curry",
      price: 130,
      text: "Rich and creamy mushroom curry, perfect with rice or roti.",
      image: "/images/mushroom.png",
      type: "dinner, lunch",
    },
    {
      name: "Pasta",
      price: 100,
      text: "Italian pasta cooked with a delicious sauce and fresh vegetables.",
      image: "/images/pasta.png",
      type: "breakfast",
    },
    {
      name: "Smoothie",
      price: 90,
      text: "A refreshing and healthy drink made with blended fruits.",
      image: "/images/smoothie.png",
      type: "midnight snack",
    },
    {
      name: "Oatmeal",
      price: 70,
      text: "A warm, healthy breakfast made with oats and milk.",
      image: "/images/oats.png",
      type: "breakfast, midnight snack",
    },
    {
      name: "Banana",
      price: 10,
      text: "A quick and healthy snack rich in potassium and energy.",
      image: "/images/banana.png",
      type: "midnight snack",
    },
  ];
  